# Build Stage

FROM node:alpine as build-stage

WORKDIR /

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production Stage

FROM nginx:alpine

COPY --from=build-stage /dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]