version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: frontend
    depends_on:
      - api
    volumes:
      - django-static:/usr/share/nginx/html/static
  
  api:
    build: api
    depends_on:
      - db
    volumes:
      - django-static:/app/static
  
  gateway:
    build: gateway
    ports:
      - "8082:80"
    depends_on:
      - api
      - web
  adminer:
    image: adminer
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  db-data:
  django-static:
