version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: frontend
    depends_on:
      - api
    volumes:
      - django-static:/usr/share/nginx/html/static
      - django-media:/usr/share/nginx/html/media
  
  api:
    build: api
    depends_on:
      - db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - django-static:/app/static
      - django-media:/app/media
  
  gateway:
    build: gateway
    ports:
      - "8080:80"
    depends_on:
      - api
      - web
  adminer:
    image: adminer
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  db-data:
  django-static:
  django-media:
