name: Update changelog

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Auto Changelog
        uses: ardalanamini/auto-changelog@v4.0.1
        with:
          release-name: v1.0.0
